//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mwc.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationClientBranch
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
        public bool IsCurrentBranch { get; set; }
        public string HeadOfficeCode { get; set; }
        public Nullable<bool> IsHeadOffice { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string AccountNo { get; set; }
        public string VATRegistrationNo { get; set; }
        public string Website { get; set; }
        public System.DateTime SetDate { get; set; }
        public string EntryUserName { get; set; }
    }
}
