//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mwc.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUserDetail
    {
        public long UserId { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public Nullable<System.DateTime> LastLogInDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }
        public Nullable<System.DateTime> LastLockOutDate { get; set; }
        public bool IsLoggedIn { get; set; }
        public int FailedPasswordAttemptCount { get; set; }
        public Nullable<System.DateTime> FailedPasswordAttemptWindowStart { get; set; }
        public int FailedPasswordAnswerAttemptCount { get; set; }
        public Nullable<System.DateTime> FailedPasswordAswerAttemptWindowStart { get; set; }
        public string EmailAddress { get; set; }
        public byte CurrentTheme { get; set; }
        public System.DateTime SetDate { get; set; }
        public string EntryUserName { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}
