//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mwc.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationClient
    {
        public byte ClientId { get; set; }
        public string ClientName { get; set; }
        public string ApplicationKey { get; set; }
        public Nullable<System.DateTime> ClientDate { get; set; }
    }
}
