//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mwc.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUser
    {
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string UserFullName { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public string EmployeeID { get; set; }
        public int RoleId { get; set; }
        public bool IsActive { get; set; }
        public bool IsLockedOut { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime SetDate { get; set; }
        public string EntryUserName { get; set; }
    
        public virtual UserRoleList UserRoleList { get; set; }
        public virtual ApplicationUserDetail ApplicationUserDetail { get; set; }
    }
}
