//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mwc.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MWCEntities : DbContext
    {
        public MWCEntities()
            : base("name=MWCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationClient> ApplicationClients { get; set; }
        public virtual DbSet<ApplicationClientBranch> ApplicationClientBranches { get; set; }
        public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public virtual DbSet<ApplicationUserDetail> ApplicationUserDetails { get; set; }
        public virtual DbSet<PictureGallery> PictureGalleries { get; set; }
        public virtual DbSet<PictureGalleryItem> PictureGalleryItems { get; set; }
        public virtual DbSet<RoleWiseScreenPermission> RoleWiseScreenPermissions { get; set; }
        public virtual DbSet<Screen> Screens { get; set; }
        public virtual DbSet<UserRoleList> UserRoleLists { get; set; }
        public virtual DbSet<Website_Notice> Website_Notice { get; set; }
        public virtual DbSet<WebSiteBanner> WebSiteBanners { get; set; }
    }
}
