//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mwc.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website_Notice
    {
        public int NoticeId { get; set; }
        public string NoticeTitle { get; set; }
        public string NoticeTitleBN { get; set; }
        public string NoticeDetails { get; set; }
        public string NoticeDetailsBN { get; set; }
        public Nullable<bool> IsShowScrollBar { get; set; }
        public string NoticeAttachment { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public string NoticeType { get; set; }
    }
}
